spring.application.name=patient-management

#spring.datasource.url=jdbc:postgresql://localhost:5432/Patient-Management
#spring.datasource.username=postgres
#spring.datasource.password=Hemant@123
#spring.jpa.show-sql=true
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto = update
#spring.sql.init.mode=always

server.port = 4000
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
logging.level.root = info

#tell that we want all info warn and error messages be logged to the terminal or console.
